#var, use command >Rest Client: Switch Environment in search bar of vs code
@id =1

###

### Get all final-works
GET http://localhost:3000/api/v1/final-works HTTP/1.1
Content-Type: application/json

###

### Get final-work by ID
GET http://localhost:3000/api/v1/final-works/{{id}} HTTP/1.1
Content-Type: application/json

###

### Create a new final-work
POST http://localhost:3000/api/v1/final-works HTTP/1.1
Content-Type: application/json

{
"title": "Analysis of Machine Learning Algorithms for Natural Language Processing",
  "status": "in_progress",
  "type": "thesis",
  "date": "2025-04-15T10:00:00.000Z",
  "userId": "65d4912a1309b10b4c6d2b65",
  "evidence": [
    {
      "download": "/downloads/document1.pdf",
      "idFile": "file12345",
      "link": "https://example.com/files/document1.pdf",
      "name": "Literature Review",
      "type": "document",
      "uri": "/storage/document1.pdf"
    },
    {
      "download": "/downloads/presentation.pptx",
      "idFile": "file67890",
      "name": "Initial Proposal",
      "type": "presentation",
      "uri": "/storage/presentation.pptx"
    }
  ]
}

###

### Update an existing final-work
PUT http://localhost:3000/api/v1/final-works/{{id}} HTTP/1.1
Content-Type: application/json

{
"title": "Analysis of Machine Learning Algorithms for Natural Language Processing",
  "status": "in_progress",
  "type": "thesis",
  "date": "2025-04-15T10:00:00.000Z",
  "userId": "65d4912a1309b10b4c6d2b65",
  "evidence": [
    {
      "download": "/downloads/document1.pdf",
      "idFile": "file12345",
      "link": "https://example.com/files/document1.pdf",
      "name": "Literature Review",
      "type": "document",
      "uri": "/storage/document1.pdf"
    },
    {
      "download": "/downloads/presentation.pptx",
      "idFile": "file67890",
      "name": "Initial Proposal",
      "type": "presentation",
      "uri": "/storage/presentation.pptx"
    }
  ]
}

###

### Update an existing final-work
PUT http://localhost:3000/api/v1/final-works/{{id}} HTTP/1.1
Content-Type: application/json

{
  "title": "Updated Analysis of Machine Learning Algorithms for NLP",
  "status": "completed",
  "type": "thesis",
  "date": "2025-04-18T14:30:00.000Z",
  "evidence": [
    {
      "download": "/downloads/document1.pdf",
      "idFile": "file12345",
      "link": "https://example.com/files/document1.pdf",
      "name": "Literature Review",
      "type": "document",
      "uri": "/storage/document1.pdf"
    },
    {
      "download": "/downloads/presentation.pptx",
      "idFile": "file67890",
      "name": "Initial Proposal",
      "type": "presentation",
      "uri": "/storage/presentation.pptx"
    },
    {
      "download": "/downloads/final_report.pdf",
      "idFile": "file24680",
      "link": "https://example.com/files/final_report.pdf",
      "name": "Final Report",
      "type": "document",
      "uri": "/storage/final_report.pdf"
    }
  ]
}

###

### Delete a final-work
DELETE http://localhost:3000/api/v1/final-works/{{id}} HTTP/1.1
Content-Type: application/json
