version: "0.2"
language: en

ignorePaths:
  # Temporary paths
  - "**/frontend"

  # Files to remove later
  - "**/*.yml"
  - "**/*.md"
  - "**/*.mdx"
  # - "*.ts"
  # - "*.tsx"
  # - "*.js"
  # - "*.jsx"

  # Common files and directories
  - "*.min.*"
  - "**/*.svg"
  - "**/*.css"
  - "**/docs/**"
  - "*.prisma"

  # Standard directories and files to ignore
  - "**/node_modules"
  - "**/test"
  - "./project-words.txt"
  - "./packages/database/prisma/generated"
  - "*package.json"
  - "*.http"
  - "*.bat"
  - .git
  - coverage
  - build
  - dist
  - "pnpm-workspace.yaml"
  - "package-lock.json"
  - "pnpm-lock.yaml"
  - "yarn.lock"

dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
dictionaries:
  - en_US
  - project-words
words: []
ignoreWords: []
import: []
