volumes:
  traefik_certs:


networks:
  gcalidad-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

services:
  proxy:
    image: traefik:2.11
    container_name: traefik
    command:
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      # Certificate Resolvers
      - "--certificatesresolvers.le.acme.email=stemsrb@una.cr"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

    ports:
      - "80:80"
      - "443:443"

    networks:
      gcalidad-network:
        ipv4_address: 172.30.0.40

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
      - ./traefik:/etc/traefik/dynamic:ro

  frontend:
    container_name: agr-frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile

    env_file:
      - ./apps/frontend/.env.production

    networks:
      gcalidad-network:
        ipv4_address: 172.30.0.30

    labels:
      # Core Traefik labels
      - "traefik.enable=true"
      - "traefik.docker.network=gcalidad-network"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

      # HTTP to HTTPS redirect
      - "traefik.http.routers.frontend-http.rule=Host(`gestion-calidad.arayaroma.software`)"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.routers.frontend-http.middlewares=redirect-scheme@file"

      # HTTPS router
      - "traefik.http.routers.frontend.rule=Host(`gestion-calidad.arayaroma.software`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.middlewares=secure-headers@file"

  backend:
    container_name: agr-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}

    env_file:
      - ./apps/backend/.env.production
      - ./.env

    networks:
      gcalidad-network:
        ipv4_address: 172.30.0.20

    labels:
      # Core Traefik labels
      - "traefik.enable=true"
      - "traefik.docker.network=gcalidad-network"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

      # HTTP to HTTPS redirect
      - "traefik.http.routers.backend-http.rule=Host(`api-gestion-calidad.arayaroma.software`)"
      - "traefik.http.routers.backend-http.entrypoints=web"
      - "traefik.http.routers.backend-http.middlewares=redirect-scheme@file"

      # HTTPS router
      - "traefik.http.routers.backend.rule=Host(`api-gestion-calidad.arayaroma.software`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.middlewares=secure-headers@file"
