#var, use command >Rest Client: Switch Environment in search bar of vs code
@id=1
@academicLoadId=1
@professorId=1

###

### Get all final-reports
GET http://localhost:3000/api/v1/final-reports?page=1&limit=10 HTTP/1.1
Content-Type: application/json

###

### Get final-report by ID
GET http://localhost:3000/api/v1/final-reports/{{id}} HTTP/1.1
Content-Type: application/json

###

### Create a new final-report
POST http://localhost:3000/api/v1/final-reports HTTP/1.1
Content-Type: application/json
{
  "academicLoadId": "{{academicLoadId}}",
  "professorId": "{{professorId}}",
  "statistics": {
    "passed": 12,
    "failed": 5,
    "dropouts": 3,
    "totalStudents": 20
  },
  "evaluation": [
    {
      "questionGroup": "Evaluación del Curso",
      "questionId": "p1",
      "options": [
        {
          "category": "calidad",
          "label": "Excelente",
          "value": "5"
        },
        {
          "category": "calidad",
          "label": "Bueno",
          "value": "4"
        }
      ],
      "otherResponse": "",
      "question": "¿Cómo calificaría los materiales del curso?",
      "response": "5",
      "multipleResponse": [],
      "responseType": "single"
    },
    {
      "questionGroup": "Participación Estudiantil",
      "questionId": "p2",
      "options": [
        {
          "category": "participación",
          "label": "Alta",
          "value": "alta"
        },
        {
          "category": "participación",
          "label": "Media",
          "value": "media"
        }
      ],
      "otherResponse": "La mayoría de los estudiantes mostraron interés en las sesiones prácticas.",
      "question": "¿Cómo describiría la participación estudiantil?",
      "response": "alta",
      "multipleResponse": ["alta", "media"],
      "responseType": "multiple"
    }
  ],
  "studentInformation": {
    "adjustments": [
      {
        "support": "Tiempo extendido",
        "idNumber": "12345",
        "name": "Juan Pérez",
        "grade": "A",
        "observation": "El estudiante necesitó tiempo adicional para los exámenes"
      }
    ],
    "safeguards": [
      {
        "idNumber": "67890",
        "name": "María López",
        "grade": "B",
        "observation": "La estudiante necesitó materiales de apoyo adicionales"
      }
    ]
  },
  "status": "PENDING"
}

###

### Delete a final-report
DELETE http://localhost:3000/api/v1/final-reports/{{id}} HTTP/1.1
Content-Type: application/json