#var, use command >Rest Client: Switch Environment in search bar of vs code
@id=1
@schoolId=1
@careerId=1

###

### Get all courses
GET http://localhost:3000/api/v1/courses?page=1&limit=10  HTTP/1.1
Content-Type: application/json

###

### Get course by ID
GET http://localhost:3000/api/v1/courses/{{id}} HTTP/1.1
Content-Type: application/json

###

### Create a new course
POST http://localhost:3000/api/v1/courses HTTP/1.1
Content-Type: application/json

{
  "code" : "CS101", 
  "name": "Introducción a la Programación",
  "description": "Un curso básico sobre conceptos de programación.",
  "credits": 3,
  "level": "Pregrado",
  "contactHours": 45,
  "schoolId": "68362646e5b3c3956494ca38",
  "careerId": "683626b1e5b3c3956494ca39",
  "status" : "ACTIVE"
}

###

### Update an existing course
PUT http://localhost:3000/api/v1/courses/{{id}} HTTP/1.1
Content-Type: application/json

{
  "code" : "CS101",
  "name": "Programación Avanzada",
  "description": "Un curso avanzado sobre conceptos de programación.",
  "credits": 4,
  "level": "Posgrado",
  "contactHours": 60,
  "schoolId": "{{schoolId}}",
  "careerId": "{{careerId}}",
  "status" : "ACTIVE"
}

###

### Delete a course
DELETE http://localhost:3000/api/v1/courses/{{id}} HTTP/1.1
Content-Type: application/json
