#var, use command >Rest Client: Switch Environment in search bar of vs code
@id =1

###

### Get all academic loads
GET http://localhost:3000/api/v1/academic_loads HTTP/1.1
Content-Type: application/json

###

### Get academic load by ID
GET http://localhost:3000/api/v1/academic_loads/{{id}} HTTP/1.1
Content-Type: application/json

###

### Create a new academic load
POST http://localhost:3000/api/v1/academic_loads HTTP/1.1
Content-Type: application/json

{
    "availableSeats": 25,
    "enrollmentCap": 30,
    "maximumCap": 35,
    "courseNumber": "ING-432",
    "status": "ACTIVE",
    "classroomId": "{{classroomId}}",
    "campusId": "{{campusId}}",
    "academicPeriod Id": "{{academicPeriod Id}}",
    "courseId": "{{courseId}}",
    "groupId": "{{groupId}}",
    "scheduleId": "{{scheduleId}}",
    "professorId": "{{professorId}}",
    "name": "Ingeniería de Software I"
}

###

### Update an existing academic load
PUT http://localhost:3000/api/v1/academic_loads/{{id}} HTTP/1.1
Content-Type: application/json

{
    "availableSeats": 20,
    "enrollmentCap": 30,
    "status": "ACTIVE",
    "name": "Ingeniería de Software I - Updated"
}

###

### Delete an academic load
DELETE http://localhost:3000/api/v1/academic_loads/{{id}} HTTP/1.1
Content-Type: application/json