#var, use "command >Rest Client: Switch Environment" in search bar of vs code
@id =1
@userId=1
@commissionId=1

###

### Get all commission-members
GET http://localhost:3000/api/v1/commission-members HTTP/1.1
Content-Type: application/json

###

### Get commission-member by ID
GET http://localhost:3000/api/v1/commission-members/{{id}} HTTP/1.1
Content-Type: application/json

###

### Create a new commission-member
POST http://localhost:3000/api/v1/commission-members HTTP/1.1
Content-Type: application/json

{
  "userId": "{{userId}}",
  "workload": "Tiempo completo",
  "commissionId": "{{commissionId}}",
  "status": "ACTIVE"
}

###

### Update an existing commission-member
PUT http://localhost:3000/api/v1/commission-members/{{id}} HTTP/1.1
Content-Type: application/json

{
  "userId": "{{userId}}",
  "workload": "Medio tiempo",
  "commissionId": "{{commissionId}}",
  "status": "ACTIVE"
}

###

### Delete a commission-member
DELETE http://localhost:3000/api/v1/commission-members/{{id}} HTTP/1.1
Content-Type: application/json
