import { MiddlewareConsumer, Module, NestModule } from '@nestjs/common';

import { LoggerMiddleware } from '@core/http/middlewares/logger.middleware';

import { AppController } from './app.controller';
import { PrismaModule } from './prisma/prisma.module';

import { JwtModule } from '@nestjs/jwt';
import { ConfigModule } from '@nestjs/config';
import { AuthModule } from '@modules/auth/auth.module';
import { ScheduleModule } from '@nestjs/schedule';

import {
  AcademicBackgroundsModule,
  AcademicCyclesModule,
  AcademicLoadGroupsModule,
  AcademicLoadsModule,
  CampusesModule,
  CareersModule,
  ClassroomsModule,
  CommMembersModule,
  CommSessionAttendancesModule,
  CommSessionsModule,
  CommissionsModule,
  CoursesModule,
  DocumentsModule,
  FacultiesModule,
  FinalReportsModule,
  FinalWorksModule,
  IntellectualProductionsModule,
  ObservationsModule,
  ParametersModule,
  PpaasModule,
  ProjectLogsModule,
  ProjectReviewsModule,
  ProjectsModule,
  QuestionGroupsModule,
  QuestionsModule,
  RegionalCentersModule,
  SchedulesModule,
  SchoolsModule,
  UserLanguagesModule,
  UserPermissionsModule,
  UserRolesModule,
  UserWorkExperiencesModule,
  UsersModule,
  // SINAES Quality Management Modules
  DimensionsModule,
  ComponentsModule,
  CriteriaModule,
  StandardsModule,
  QualityEvidencesModule,
  ProofDocumentTypesModule,
  DocumentCountersModule,
  ProofDocumentsModule,
  CareerProofDocumentsModule,
  StandardEvidencesModule,
  GoogleDriveFoldersModule,
  SinaesReportsModule,
  SinaesDocumentHistoryModule,
  // Tiempos
  AnnualJourneyTimeAllocationsModule,
  CampusJourneyTimeAllocationsModule,
  ProfessorAssignmentsModule,
  JourneyTimeConfigsModule,
  ExternalProvidersModule,
  InstitutionalProjectsModule,
  TimesModule,
  GoogleDriveModule,
} from '@modules/index';

@Module({
  imports: [
    PrismaModule,
    AuthModule,
    JwtModule.register({}),
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    AcademicBackgroundsModule,
    AcademicCyclesModule,
    AcademicLoadGroupsModule,
    AcademicLoadsModule,
    CampusesModule,
    CareersModule,
    ClassroomsModule,
    CommMembersModule,
    CommSessionAttendancesModule,
    CommSessionsModule,
    CommissionsModule,
    CoursesModule,
    DocumentsModule,
    FacultiesModule,
    FinalReportsModule,
    FinalWorksModule,
    IntellectualProductionsModule,
    ObservationsModule,
    ParametersModule,
    PpaasModule,
    ProjectLogsModule,
    ProjectReviewsModule,
    ProjectsModule,
    QuestionGroupsModule,
    QuestionsModule,
    RegionalCentersModule,
    SchedulesModule,
    SchoolsModule,
    UserLanguagesModule,
    UserPermissionsModule,
    UserRolesModule,
    UserWorkExperiencesModule,
    UsersModule,
    ProfessorAssignmentsModule,
    // SINAES Quality Management Modules
    DimensionsModule,
    ComponentsModule,
    CriteriaModule,
    StandardsModule,
    QualityEvidencesModule,
    ProofDocumentTypesModule,
    DocumentCountersModule,
    ProofDocumentsModule,
    CareerProofDocumentsModule,
    StandardEvidencesModule,
    GoogleDriveFoldersModule,
    SinaesReportsModule,
    SinaesDocumentHistoryModule,
    GoogleDriveModule,
    ScheduleModule.forRoot(),
    // TIEMPOS
    AnnualJourneyTimeAllocationsModule,
    CampusJourneyTimeAllocationsModule,
    ProfessorAssignmentsModule,
    JourneyTimeConfigsModule,
    ExternalProvidersModule,
    InstitutionalProjectsModule,
    TimesModule,
  ],
  controllers: [AppController],
})
export class AppModule implements NestModule {
  configure(consumer: MiddlewareConsumer) {
    consumer.apply(LoggerMiddleware).forRoutes('*');
  }
}
